# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 385dcb6b973de42e38413a3efe5b528f483076c69bb5bdcf83ea8422897b3bdb57ec015784d7aa7e68ba1d3cc4fb63d2e9c826f7f001e87a37c70046e1e9a026

test:
  secret_key_base: 19707ecb9bc67a54f92192c85985f990dba5d0b7b2f5151fb56a21191d36a4b347246aad19fa1bf6b3e4cb10eec19b1718c7e76dfaa8ed5bdbc7f0dfac1121b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
